# Generated by Django 4.2.11 on 2026-04-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeiroContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('como_conheceu', models.CharField(blank=True, max_length=180)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('primeiro_contato', 'Primeiro contato'), ('em_acompanhamento', 'Em acompanhamento'), ('membro', 'Membro')], default='primeiro_contato', max_length=30)),
                ('data_primeiro_contato', models.DateField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Primeiro contato',
                'verbose_name_plural': 'Primeiros contatos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
