# Generated by Django 4.2.11 on 2026-04-01 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteracaoAcolhimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tentativa_contato', 'Tentativa de contato'), ('resposta_recebida', 'Resposta recebida'), ('visita_agendada', 'Visita agendada'), ('visita_realizada', 'Visita realizada'), ('observacao', 'Observação')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('data_interacao', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='acolhimento.primeirocontato')),
            ],
            options={
                'verbose_name': 'Interação de acolhimento',
                'verbose_name_plural': 'Interações de acolhimento',
                'ordering': ['-data_interacao', '-criado_em'],
            },
        ),
    ]
