# Generated by Django 4.2.11 on 2026-04-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0002_interacaoacolhimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeirocontato',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('uniao_estavel', 'Uniao estavel'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viuvo(a)')], max_length=20),
        ),
        migrations.AddField(
            model_name='primeirocontato',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AddField(
            model_name='primeirocontato',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='primeirocontato',
            name='religiao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
