# Generated by Django 4.2.11 on 2026-04-01 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0003_primeirocontato_estado_civil_primeirocontato_genero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primeirocontato',
            old_name='telefone',
            new_name='telefone_whatsapp',
        ),
        migrations.AlterField(
            model_name='primeirocontato',
            name='telefone_whatsapp',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Informe um telefone/WhatsApp valido com DDD. Ex.: (31) 99999-9999', regex='^\\(?[1-9]{2}\\)?\\s?9?\\d{4}-?\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='primeirocontato',
            name='o_que_busca',
            field=models.CharField(choices=[('conhecer_deus', 'Conhecer Deus'), ('fazer_amizades', 'Fazer amizades'), ('restaurar_vida', 'Restaurar vida'), ('apoio_emocional', 'Apoio emocional'), ('participar_de_algo', 'Participar de algo')], default='conhecer_deus', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primeirocontato',
            name='primeira_vez',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='primeirocontato',
            name='como_conheceu',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('indicacao', 'Indicacao'), ('passando_na_rua', 'Passando na rua'), ('evento', 'Evento'), ('outro', 'Outro')], max_length=20),
        ),
    ]
