# Generated by Django 4.2.11 on 2026-04-01 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acolhimento', '0004_remove_primeirocontato_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeirocontato',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastros_primeiro_contato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='primeirocontato',
            name='origem_cadastro',
            field=models.CharField(choices=[('equipe', 'Equipe'), ('auto_cadastro', 'Auto cadastro')], default='equipe', max_length=20),
        ),
    ]
