# Generated by Django 4.2.11 on 2026-04-01 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acolhimento', '0006_primeirocontato_responsavel_atual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], default='whatsapp', max_length=20)),
                ('direcao', models.CharField(choices=[('saida', 'Saida'), ('entrada', 'Entrada')], default='saida', max_length=20)),
                ('status_fila', models.CharField(choices=[('pendente', 'Pendente'), ('agendada', 'Agendada'), ('processando', 'Processando'), ('enviada', 'Enviada'), ('falha', 'Falha'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('prioridade', models.PositiveSmallIntegerField(default=5)),
                ('conteudo', models.TextField()),
                ('referencia_externa', models.CharField(blank=True, max_length=120)),
                ('tentativas_envio', models.PositiveSmallIntegerField(default=0)),
                ('erro_ultimo_envio', models.TextField(blank=True)),
                ('agendada_para', models.DateTimeField(blank=True, null=True)),
                ('enfileirada_em', models.DateTimeField(auto_now_add=True)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('resposta_recebida_em', models.DateTimeField(blank=True, null=True)),
                ('resposta_conteudo', models.TextField(blank=True)),
                ('metadata_envio', models.JSONField(blank=True, default=dict)),
                ('metadata_resposta', models.JSONField(blank=True, default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='acolhimento.campanhacomunicacao')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_criadas', to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='acolhimento.primeirocontato')),
            ],
            options={
                'verbose_name': 'Mensagem de contato',
                'verbose_name_plural': 'Mensagens de contato',
                'ordering': ['status_fila', 'prioridade', 'agendada_para', 'enfileirada_em'],
                'indexes': [models.Index(fields=['status_fila', 'agendada_para'], name='acolhimento_status__f45b89_idx'), models.Index(fields=['pessoa', 'enviada_em'], name='acolhimento_pessoa__7b91b6_idx'), models.Index(fields=['direcao', 'canal'], name='acolhimento_direcao_1a35a4_idx')],
            },
        ),
    ]
