# Generated by Django 4.2.11 on 2026-04-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0007_mensagemcontato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primeirocontato',
            name='status',
            field=models.CharField(choices=[('primeiro_contato', 'Primeiro contato'), ('robo', 'Robo'), ('em_acompanhamento', 'Em acompanhamento'), ('membro', 'Membro')], default='primeiro_contato', max_length=30),
        ),
    ]
