# Generated by Django 4.2.11 on 2026-04-02 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0008_alter_primeirocontato_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoProcessamentoFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('executando', 'Executando'), ('concluida', 'Concluida'), ('interrompida', 'Interrompida'), ('falha', 'Falha')], default='executando', max_length=20)),
                ('limite', models.PositiveIntegerField(default=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('ids_filtrados', models.JSONField(blank=True, default=list)),
                ('total_selecionado', models.PositiveIntegerField(default=0)),
                ('total_processado', models.PositiveIntegerField(default=0)),
                ('total_sucesso', models.PositiveIntegerField(default=0)),
                ('total_falha', models.PositiveIntegerField(default=0)),
                ('solicitar_parada', models.BooleanField(default=False)),
                ('log_execucao', models.TextField(blank=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_fila_mensagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execucao de processamento da fila',
                'verbose_name_plural': 'Execucoes de processamento da fila',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
