# Generated by Django 4.2.11 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0009_execucaoprocessamentofila'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemcontato',
            name='visualizada_equipe_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
