# Generated by Codex on 2026-07-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0012_alter_primeirocontato_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primeirocontato',
            options={
                'ordering': ['-criado_em'],
                'permissions': [
                    ('pode_conversar_pessoas', 'Pode ver e enviar mensagens das pessoas'),
                ],
                'verbose_name': 'Primeiro contato',
                'verbose_name_plural': 'Primeiros contatos',
            },
        ),
    ]
