# Generated by Django 4.2.11 on 2026-07-27 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acolhimento', '0013_alter_primeirocontato_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questionario',
                'verbose_name_plural': 'Questionarios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('ajuda', models.CharField(blank=True, max_length=300)),
                ('tipo', models.CharField(choices=[('texto_curto', 'Texto curto'), ('texto_longo', 'Texto longo'), ('escolha_unica', 'Escolha unica'), ('data', 'Data'), ('sim_nao', 'Sim / Nao')], default='texto_curto', max_length=20)),
                ('obrigatoria', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='acolhimento.questionario')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='acolhimento.perguntaquestionario')),
            ],
            options={
                'verbose_name': 'Opcao de pergunta',
                'verbose_name_plural': 'Opcoes de pergunta',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConviteQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('respondido', 'Respondido')], default='pendente', max_length=20)),
                ('respondente_nome', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_questionario_criados', to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_questionario', to='acolhimento.primeirocontato')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='acolhimento.questionario')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_questionario_respondidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite de questionario',
                'verbose_name_plural': 'Convites de questionario',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True)),
                ('convite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='acolhimento.convitequestionario')),
                ('opcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='acolhimento.opcaopergunta')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='acolhimento.perguntaquestionario')),
            ],
            options={
                'verbose_name': 'Resposta de pergunta',
                'verbose_name_plural': 'Respostas de pergunta',
                'unique_together': {('convite', 'pergunta')},
            },
        ),
    ]
