# Generated by Codex on 2026-07-27

import datetime

import apps.acolhimento.models
from django.db import migrations, models
from django.utils import timezone


def preencher_hora_interacao(apps, schema_editor):
	InteracaoAcolhimento = apps.get_model('acolhimento', 'InteracaoAcolhimento')
	for interacao in InteracaoAcolhimento.objects.all().only('id', 'criado_em'):
		hora = datetime.time(0, 0)
		if interacao.criado_em:
			hora = timezone.localtime(interacao.criado_em).time().replace(microsecond=0)
		InteracaoAcolhimento.objects.filter(pk=interacao.pk).update(hora_interacao=hora)


class Migration(migrations.Migration):

	dependencies = [
		('acolhimento', '0014_questionario_perguntaquestionario_opcaopergunta_and_more'),
	]

	operations = [
		migrations.AddField(
			model_name='interacaoacolhimento',
			name='hora_interacao',
			field=models.TimeField(blank=True, null=True),
		),
		migrations.RunPython(preencher_hora_interacao, migrations.RunPython.noop),
		migrations.AlterField(
			model_name='interacaoacolhimento',
			name='hora_interacao',
			field=models.TimeField(default=apps.acolhimento.models.hora_local_atual),
		),
		migrations.AlterModelOptions(
			name='interacaoacolhimento',
			options={
				'ordering': ['-data_interacao', '-hora_interacao', '-criado_em'],
				'verbose_name': 'Interação de acolhimento',
				'verbose_name_plural': 'Interações de acolhimento',
			},
		),
	]
