# Generated by Django 4.2.11 on 2026-08-01 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acolhimento', '0015_interacaoacolhimento_hora_interacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('primeiro_contato_opt_in', 'Primeiro contato (opt-in)'), ('continuar_conversa', 'Continuar conversa')], max_length=40, unique=True)),
                ('content_sid', models.CharField(blank=True, max_length=64, verbose_name='Content Template SID')),
                ('content_variables', models.TextField(blank=True, default='{}', verbose_name='Variaveis (JSON)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_whatsapp_atualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template do WhatsApp',
                'verbose_name_plural': 'Templates do WhatsApp',
            },
        ),
    ]
