# Generated by Django 4.2.11 on 2026-08-12 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acolhimento', '0016_templatewhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaoprocessamentofila',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automatico')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracaoProcessamentoFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_ativo', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracao do processamento da fila',
                'verbose_name_plural': 'Configuracao do processamento da fila',
            },
        ),
    ]
