# Generated by Django 4.2.11 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0017_execucaoprocessamentofila_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatewhatsapp',
            name='texto_evolution',
            field=models.TextField(blank=True, verbose_name='Texto WhatsApp'),
        ),
    ]
