# Generated by Django 4.2.11 on 2026-08-13 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acolhimento', '0018_templatewhatsapp_texto_evolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoAtendimentoBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('rotulo', models.CharField(max_length=80, verbose_name='Rotulo no menu')),
                ('palavras_chave', models.TextField(blank=True, help_text='Aliases que acionam a opcao (separados por virgula ou linha). O numero da opcao sempre funciona.', verbose_name='Palavras-chave')),
                ('resposta', models.TextField(verbose_name='Resposta enviada')),
                ('acao', models.CharField(choices=[('responder', 'So responder'), ('transferir_humano', 'Transferir para atendente')], default='responder', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opcao do atendimento automatico',
                'verbose_name_plural': 'Opcoes do atendimento automatico',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='primeirocontato',
            name='bot_etapa',
            field=models.CharField(choices=[('inativo', 'Inativo'), ('menu', 'Aguardando escolha no menu')], default='inativo', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracaoAtendimentoBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('mensagem_saudacao', models.TextField(default='Ola! Que bom falar com voce. Com o que posso te ajudar hoje?', verbose_name='Mensagem de saudacao')),
                ('mensagem_fallback', models.TextField(default='Nao entendi. Responda com o numero de uma das opcoes abaixo:', verbose_name='Mensagem quando nao entende')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracao do atendimento automatico',
                'verbose_name_plural': 'Configuracao do atendimento automatico',
            },
        ),
    ]
