# Generated by Django 4.2.11 on 2026-08-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0020_seed_atendimento_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoprocessamentofila',
            name='delay_digitando_max_ms',
            field=models.PositiveIntegerField(default=3500),
        ),
        migrations.AddField(
            model_name='configuracaoprocessamentofila',
            name='delay_digitando_min_ms',
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='configuracaoprocessamentofila',
            name='intervalo_max_seg',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='configuracaoprocessamentofila',
            name='intervalo_min_seg',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='configuracaoprocessamentofila',
            name='janela_envio_fim',
            field=models.PositiveSmallIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='configuracaoprocessamentofila',
            name='janela_envio_inicio',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='configuracaoprocessamentofila',
            name='teto_diario',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
