# Generated by Django 4.2.11 on 2026-08-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0021_configuracaoprocessamentofila_delay_digitando_max_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeirocontato',
            name='whatsapp_lid',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
