# Generated by Django 4.2.11 on 2026-08-29 10:20

from django.db import migrations, models

TITULO_MEMBRESIA = 'Formulario de Membresia'


def marcar_membresia_existente(apps, schema_editor):
    """Marca o formulario ja criado pelo comando `popular_questionario_membresia`."""
    Questionario = apps.get_model('acolhimento', 'Questionario')
    existente = Questionario.objects.filter(titulo=TITULO_MEMBRESIA).order_by('pk').first()
    if existente is not None:
        existente.padrao_membresia = True
        existente.save(update_fields=['padrao_membresia'])


def desmarcar_membresia(apps, schema_editor):
    Questionario = apps.get_model('acolhimento', 'Questionario')
    Questionario.objects.filter(padrao_membresia=True).update(padrao_membresia=False)


class Migration(migrations.Migration):

    dependencies = [
        ('acolhimento', '0022_primeirocontato_whatsapp_lid'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='padrao_membresia',
            field=models.BooleanField(default=False, help_text='Gerado automaticamente quando a pessoa passa para o status Participante.', verbose_name='Questionario de membresia'),
        ),
        migrations.RunPython(marcar_membresia_existente, desmarcar_membresia),
    ]
