# Generated by Django 4.2.11 on 2026-08-15 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, editable=False, help_text='Identificador fixo usado na URL publica do QR Code.', max_length=16, unique=True, verbose_name='codigo')),
                ('nome', models.CharField(help_text='Nome interno para identificar o QR Code (ex.: Cartaz da entrada).', max_length=120, verbose_name='nome')),
                ('destino', models.URLField(help_text='Para onde o QR Code deve redirecionar quando for escaneado.', max_length=2000, verbose_name='URL de destino')),
                ('ativo', models.BooleanField(default=True, help_text='Se desativado, o QR Code para de redirecionar.', verbose_name='ativo')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao')),
                ('total_acessos', models.PositiveIntegerField(default=0, editable=False, verbose_name='total de acessos')),
                ('ultimo_acesso', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ultimo acesso')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrcodes_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
