"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# O fallback abaixo e SO para desenvolvimento (DEBUG=True). Em producao a chave
# precisa vir do ambiente (validado logo depois de DEBUG).
_INSECURE_SECRET_KEY = 'django-insecure-@m(yg_o#4y1@j%4tefjhye7j-qwr0!*+8f9$0it2^@xv)^&rr#'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', _INSECURE_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

# Em producao nao deixamos subir com a chave de desenvolvimento (publica no repo):
# sem uma SECRET_KEY forte, sessoes e tokens CSRF ficam vulneraveis.
if not DEBUG and SECRET_KEY == _INSECURE_SECRET_KEY:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY nao configurada: defina uma chave forte e aleatoria no '
        'ambiente antes de rodar com DJANGO_DEBUG=False.'
    )

def _split_env_list(var_name: str, default: str) -> list[str]:
    raw = os.getenv(var_name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


def _env_bool(var_name: str, default: bool = False) -> bool:
    raw = os.getenv(var_name)
    if raw is None:
        return default
    return raw.strip().lower() in {'1', 'true', 'yes', 'on', 'sim'}


ALLOWED_HOSTS = _split_env_list(
    'DJANGO_ALLOWED_HOSTS',
    # host.docker.internal: permite que o container do Evolution (Docker) mande
    # webhooks para o Django rodando no host. Inofensivo em producao.
    'acolhimento.simoesti.com.br,acolhimento.pibvp.org.br,localhost,127.0.0.1,host.docker.internal',
)

CSRF_TRUSTED_ORIGINS = _split_env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'https://acolhimento.simoesti.com.br,https://acolhimento.pibvp.org.br,http://localhost:8000,http://127.0.0.1:8000,http://localhost:8080,http://127.0.0.1:8080',
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.core',
    'apps.acolhimento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must run right after SecurityMiddleware to serve collected static files in deploys.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.mensagens_retorno_pendente',
                'apps.core.context_processors.whatsapp_conexao',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.getenv('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', 'db'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': int(os.getenv('POSTGRES_CONN_MAX_AGE', '60')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# WhiteNoise serves compressed, cache-busted static files generated by collectstatic.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

PUBLIC_BASE_URL = os.getenv('PUBLIC_BASE_URL', 'https://acolhimento.simoesti.com.br').rstrip('/')

# Cabecalhos de seguranca aplicados em qualquer ambiente. Explicitos de proposito:
# assim nao dependemos dos defaults do framework (que podem mudar entre versoes).
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SESSION_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('DJANGO_SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

AUTHENTICATION_BACKENDS = [
    'apps.core.auth_backends.UsernameOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


TWILIO_ENABLED = os.getenv('TWILIO_ENABLED', 'False').lower() == 'true'
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_WHATSAPP_FROM = os.getenv('TWILIO_WHATSAPP_FROM', 'whatsapp:+14155238886')
TWILIO_STATUS_CALLBACK_URL = os.getenv('TWILIO_STATUS_CALLBACK_URL', '')
TWILIO_REQUEST_TIMEOUT_SECONDS = int(os.getenv('TWILIO_REQUEST_TIMEOUT_SECONDS', '10'))
TWILIO_TEMPLATE_OPT_IN_SID = os.getenv('TWILIO_TEMPLATE_OPT_IN_SID', '')
TWILIO_TEMPLATE_OPT_IN_VARIABLES = os.getenv('TWILIO_TEMPLATE_OPT_IN_VARIABLES', '{}')
# Template de continuacao: reabre a janela de 24h depois que ela fecha (diferente do de boas-vindas).
TWILIO_TEMPLATE_CONTINUAR_SID = os.getenv('TWILIO_TEMPLATE_CONTINUAR_SID', 'HX7e2031da82a4a61e7e887be341a3c2af')
TWILIO_TEMPLATE_CONTINUAR_VARIABLES = os.getenv('TWILIO_TEMPLATE_CONTINUAR_VARIABLES', '{}')


# ---------------------------------------------------------------------------
# Provider de WhatsApp: 'evolution' ou 'twilio'.
# Nesta branch (feat/evolution-integracao) o padrao do app e 'evolution'.
# Durante os testes o padrao volta a 'twilio': as regras de opt-in/janela sao
# semanticas da Twilio e o modo Baileys tentaria enviar de verdade (rede).
# Sempre trocavel por ambiente: WHATSAPP_PROVIDER=twilio|evolution.
# ---------------------------------------------------------------------------
_default_whatsapp_provider = 'twilio' if 'test' in sys.argv else 'evolution'
WHATSAPP_PROVIDER = os.getenv('WHATSAPP_PROVIDER', _default_whatsapp_provider).strip().lower()

# Evolution API (Baileys / WhatsApp Web). Defaults casam com evolution/docker-compose.yml.
EVOLUTION_BASE_URL = os.getenv('EVOLUTION_BASE_URL', 'http://localhost:8085').rstrip('/')
EVOLUTION_PUBLIC_URL = os.getenv('EVOLUTION_PUBLIC_URL', EVOLUTION_BASE_URL).rstrip('/')
EVOLUTION_API_KEY = os.getenv('EVOLUTION_API_KEY', 'pibvp-teste-2026')
EVOLUTION_INSTANCE = os.getenv('EVOLUTION_INSTANCE', 'pibvp-teste')
EVOLUTION_INTEGRATION = os.getenv('EVOLUTION_INTEGRATION', 'WHATSAPP-BAILEYS')
EVOLUTION_REQUEST_TIMEOUT_SECONDS = int(os.getenv('EVOLUTION_REQUEST_TIMEOUT_SECONDS', '30'))
EVOLUTION_AUTO_CONFIGURE_WEBHOOK = _env_bool('EVOLUTION_AUTO_CONFIGURE_WEBHOOK', True)
EVOLUTION_WEBHOOK_URL = os.getenv(
    'EVOLUTION_WEBHOOK_URL',
    f'{PUBLIC_BASE_URL}/acolhimento/mensagens/webhook/evolution/',
).strip()
EVOLUTION_WEBHOOK_EVENTS = _split_env_list(
    'EVOLUTION_WEBHOOK_EVENTS',
    'MESSAGES_UPSERT,MESSAGES_UPDATE',
)
EVOLUTION_WEBHOOK_BY_EVENTS = _env_bool('EVOLUTION_WEBHOOK_BY_EVENTS', False)
EVOLUTION_WEBHOOK_BASE64 = _env_bool('EVOLUTION_WEBHOOK_BASE64', False)
EVOLUTION_WEBHOOK_SECRET = os.getenv('EVOLUTION_WEBHOOK_SECRET', '').strip()
# No modo Baileys nao existe template aprovado: as mensagens de "template" da Twilio
# (opt-in / continuar) viram texto simples. {nome} e substituido pelo nome da pessoa.
EVOLUTION_TEXTO_OPTIN = os.getenv('EVOLUTION_TEXTO_OPTIN') or (
    'Ola {nome}! Aqui e o acolhimento da PIBVP. Podemos conversar por aqui?'
)
EVOLUTION_TEXTO_CONTINUAR = os.getenv('EVOLUTION_TEXTO_CONTINUAR') or (
    'Ola {nome}, tudo bem? Podemos continuar nossa conversa?'
)

# ---------------------------------------------------------------------------
# Opt-in-first (anti-bloqueio): faz a PESSOA iniciar a conversa.
# O maior fator de bloqueio e nos mandarmos a 1a mensagem para quem nunca
# escreveu. PIB_WHATSAPP_NUMERO_OPTIN e o numero da igreja (com DDI) usado no
# botao "abrir WhatsApp e falar com a gente" da tela de sucesso do auto-cadastro.
# Quando vazio, o botao nao aparece.
# ---------------------------------------------------------------------------
PIB_WHATSAPP_NUMERO_OPTIN = os.getenv('PIB_WHATSAPP_NUMERO_OPTIN', '').strip()
PIB_WHATSAPP_OPTIN_TEXTO = os.getenv('PIB_WHATSAPP_OPTIN_TEXTO') or (
    'Oi! Acabei de me cadastrar no acolhimento da PIBVP e gostaria de conversar.'
)
# Carencia (em horas) antes de incluir alguem no disparo pausado de boas-vindas:
# da tempo da pessoa iniciar a conversa sozinha pelo botao acima. 0 = sem carencia.
HORAS_ESPERA_OPTIN = int(os.getenv('HORAS_ESPERA_OPTIN') or 0)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Logging
# Saida para stdout (capturada pelo Docker/Gunicorn). Ajuste o nivel do app por
# ambiente com DJANGO_LOG_LEVEL (INFO em producao, DEBUG para investigar).
# ---------------------------------------------------------------------------
LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO').upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Codigo da aplicacao (apps.core, apps.acolhimento, ...).
        'apps': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}
