from django.urls import path

from apps.acolhimento.views import (
    AutoCadastroCreateView,
    AutoCadastroSuccessView,
    DisparoMensagemMassaView,
    EnviarConviteWhatsappView,
    EnviarTemplateContinuarView,
    ExcluirConviteQuestionarioView,
    GerarConviteQuestionarioView,
    MensagemFilaListView,
    MensagemContatoExcluirView,
    PerguntaDeleteView,
    PerguntaMoverView,
    PerguntaUpdateView,
    ProcessamentoFilaControleView,
    PrimeiroContatoEnfileirarMensagemView,
    PrimeiroContatoCreateView,
    PrimeiroContatoDeleteView,
    PrimeiroContatoDetailView,
    PrimeiroContatoExportCsvView,
    PrimeiroContatoListView,
    PrimeiroContatoMensagensMaisView,
    PrimeiroContatoMensagensView,
    PrimeiroContatoStatusUpdateView,
    PrimeiroContatoUpdateView,
    QuestionarioBuilderView,
    QuestionarioCreateView,
    QuestionarioDeleteView,
    QuestionarioListView,
    QuestionarioPreviewView,
    QuestionarioUpdateView,
    RelatorioPessoasView,
    RespostaConviteDetailView,
    TwilioInboundWebhookView,
    TwilioStatusWebhookView,
)

urlpatterns = [
    path('auto-cadastro/', AutoCadastroCreateView.as_view(), name='auto-cadastro'),
    path('auto-cadastro/sucesso/', AutoCadastroSuccessView.as_view(), name='auto-cadastro-sucesso'),
    path('pessoas/', PrimeiroContatoListView.as_view(), name='pessoas-lista'),
    path('mensagens/fila/', MensagemFilaListView.as_view(), name='mensagens-fila'),
    path('mensagens/processamento/', ProcessamentoFilaControleView.as_view(), name='mensagens-processamento'),
    path('mensagens/disparo/', DisparoMensagemMassaView.as_view(), name='mensagens-disparo-massa'),
    path('mensagens/webhook/twilio-status/', TwilioStatusWebhookView.as_view(), name='mensagens-webhook-twilio-status'),
    path('mensagens/webhook/twilio-inbound/', TwilioInboundWebhookView.as_view(), name='mensagens-webhook-twilio-inbound'),
    path('mensagens/<int:pk>/excluir/', MensagemContatoExcluirView.as_view(), name='mensagens-excluir'),
    path('pessoas/novo/', PrimeiroContatoCreateView.as_view(), name='pessoas-novo'),
    path('pessoas/relatorios/', RelatorioPessoasView.as_view(), name='pessoas-relatorios'),
    path('pessoas/<int:pk>/', PrimeiroContatoDetailView.as_view(), name='pessoas-detalhe'),
    path('pessoas/<int:pk>/mensagens/', PrimeiroContatoMensagensView.as_view(), name='pessoas-mensagens'),
    path('pessoas/<int:pk>/mensagens/carregar/', PrimeiroContatoMensagensMaisView.as_view(), name='pessoas-mensagens-carregar'),
    path('pessoas/<int:pk>/enfileirar-mensagem/', PrimeiroContatoEnfileirarMensagemView.as_view(), name='pessoas-enfileirar-mensagem'),
    path('pessoas/<int:pk>/template-continuar/', EnviarTemplateContinuarView.as_view(), name='pessoas-template-continuar'),
    path('pessoas/<int:pk>/status/', PrimeiroContatoStatusUpdateView.as_view(), name='pessoas-status'),
    path('pessoas/<int:pk>/editar/', PrimeiroContatoUpdateView.as_view(), name='pessoas-editar'),
    path('pessoas/<int:pk>/excluir/', PrimeiroContatoDeleteView.as_view(), name='pessoas-excluir'),
    path('pessoas/exportar-csv/', PrimeiroContatoExportCsvView.as_view(), name='pessoas-exportar-csv'),
    path('pessoas/<int:pk>/gerar-convite/', GerarConviteQuestionarioView.as_view(), name='pessoas-gerar-convite'),
    path('questionarios/', QuestionarioListView.as_view(), name='questionarios-lista'),
    path('questionarios/novo/', QuestionarioCreateView.as_view(), name='questionarios-novo'),
    path('questionarios/<int:pk>/', QuestionarioBuilderView.as_view(), name='questionario-builder'),
    path('questionarios/<int:pk>/visualizar/', QuestionarioPreviewView.as_view(), name='questionario-visualizar'),
    path('questionarios/<int:pk>/editar/', QuestionarioUpdateView.as_view(), name='questionario-editar'),
    path('questionarios/<int:pk>/excluir/', QuestionarioDeleteView.as_view(), name='questionario-excluir'),
    path('perguntas/<int:pk>/editar/', PerguntaUpdateView.as_view(), name='pergunta-editar'),
    path('perguntas/<int:pk>/excluir/', PerguntaDeleteView.as_view(), name='pergunta-excluir'),
    path('perguntas/<int:pk>/mover/', PerguntaMoverView.as_view(), name='pergunta-mover'),
    path('convites/<int:pk>/', RespostaConviteDetailView.as_view(), name='convite-resposta'),
    path('convites/<int:pk>/enviar-whatsapp/', EnviarConviteWhatsappView.as_view(), name='convite-enviar-whatsapp'),
    path('convites/<int:pk>/excluir/', ExcluirConviteQuestionarioView.as_view(), name='convite-excluir'),
]
